name: linearvc
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - tqdm
  - pytorch>=2.5
  - torchaudio>=2.5
  - pytorch-cuda=12.1
  - torchvision
  - onnx
  - onnxscript
  - celer
  - jupyterlab
  - ipykernel
  - ipython
  - ffmpeg
  - sox
  - libflac
  - libsndfile
  - ca-certificates
  - openssl
  - pip:
      - speechbrain
      - jiwer
      - openai-whisper
